import Colors from "./Colors";

export const AppConstants = {
  GET: "get",
  PUT: "put",
  POST: "post",
  PATCH: "patch",
  DELETE: "delete",
  // ---
  YES: "Yes",
  NO: "No",
  STATUS_SCHEDULED: "Scheduled",
  STATUS_IN_PROGRESS: "In Progress",
  STATUS_DONE: "Done",
  STATUS_DRAFT: "Draft",
  STATUS_DONE_SUCCESS: "Success",
  STATUS_DONE_FAILED: "Failed",
  STATUS_SCHEDULED_UPPERCASE: "SCHEDULED",
  STATUS_IN_PROGRESS_UPPERCASE: "IN_PROGRESS",
  STATUS_DONE_UPPERCASE: "DONE",
  STATUS_DRAFT_UPPERCASE: "DRAFT",
  STATUS_DONE_SUCCESS_UPPERCASE: "SUCCESS",
  STATUS_DONE_FAILED_UPPERCASE: "FAILED",
  STATUS_DONE_FINISHED_UPPERCASE: "FINISHED",
  STATUS_PENDING_UPPERCASE: "PENDING",
  // ---
  SIMPLE_VALUE: "SIMPLE_VALUE",
  MULTI_VALUE: "MULTI_VALUE",
  BINARY: "BINARY",
  RANGE: "RANGE",
  OBSERVATION: "OBSERVATION",
  TEST_STEP_STATUS: "TEST_STEP_STATUS",
  // ---
  TYPE_NOT_APPLICABBLE: "Not Applicabble",
  TYPE_NUMERIC_VALUE: "NumericValue",
  TYPE_STRING_VALUE: "StringValue",
  TYPE_DATE_VALUE: "DateValue",
  TYPE_NUMERIC_UNIT_VALUE: "NumericUnitValue",
  TYPE_BOOLEAN_VALUE: "BooleanValue",
  TYPE_MEASURE_UNIT: "MeasureUnit",
  // ---
  TYPE_DAILY: "Daily",
  TYPE_WEEKLY: "Weekly",
  TYPE_MONTHLY: "Monthly",
  TYPE_ANNUALLY: "Annually",
  // ---
  TYPE_NA: "N/A",
  TYPE_OBJECT: "object",
  TYPE_STRING: "string",
  TYPE_BOOLEAN: "boolean",
  TYPE_NUMERIC: "numeric",
  TYPE_TEXT: "text",
  TYPE_SET: "set",
  TYPE_DISMISSED: "dismissed",
  // ---
  ANNOTATION_RECOMMENDATIONS_TYPE: "RECOMMENDATIONS",
  ANNOTATION_DEFICIENCIES_TYPE: "DEFICIENCIES",
  ANNOTATION_REMARKS_TYPE: "REMARKS",
  RECOMMENDATION: "Recommendation",
  REMARK: "Remark",
  DEFICIENCY: "Deficiency",
  COMMUNICATION_ISSUE: "Communication Issue",
  DEVICE_ISSUE: "Device Issue",
  INSTALLATION_ISSUE: "Installation Issue",
  // ---
  MONDAY: "Monday",
  TUESDAY: "Tuesday",
  WEDNESDAY: "Wednesday",
  THURSDAY: "Thursday",
  FRIDAY: "Friday",
  WEEK: "Week",
  MONTH: "Month",
  START_DATE: "startDate",
  END_DATE: "endDate",
  // ---
  NAME: "Name",
  DESCRIPTION: "Description",
  INSPECTIONS: "Inspections",
  BUILDING: "Building",
  BUILDING_ID: "Building Id",
  ADDRESS: "Address",
  CATEGORY: "Category",
  DATE: "Date",
  WEEKDAY: "Weekday",
  FREQUENCY: "Frequency",
  SIGNED: "Signed",
  SIGNER: "Signer",
  APPROVAL_DATE: "ApprovalDate",
  SCHEDULED_DATE: "ScheduledDate",
  COVER_PAGE_NAME: "coverPageName",
  TEMPLATE: "Template",
  NOTES: "Notes",
  INSPECTION_TEMPLATE: "InspectionTemplate",
  TYPE: "Type",
  DEVICE_TYPE: "DeviceType",
  STATUS: "Status",
  RESULT: "Result",
  MODEL: "Model",
  GENERAL: "General",
  DEVICE: "Device",
  QUANTITY: "Quantity",
  LOCATION: "Location",
  ZONE: "Zone",
  CONVER_PAGE_NAME: "coverPageName",
  SERIAL_NUMBER: "Serial Number",
  INSTALLATION_DATE: "Installation Date",
  EXPIRATION_DATE: "Expiration Date",
  CLIENT: "Client",
  ATTRIBUTE: "Attribute",
  MANUFACTURER: "Manufacturer",
  TEAM: "Team",
  TESTS: "Tests",
  COVER_PAGE: "Cover Page",
  INSPECTOR: "Inspector",
  OPERATOR: "Operator",
  ABBREVIATION: "Abbreviation",
  DEFICIENCY_TYPE_ID: "deficiencyTypeId",
  // ---
  SHOWING_ALL_INSPECTIONS: "Showing All Inspections",
  LOADING_OBSERVATIONS: "Loading observations...",
  SAVING_OBSERVATION: "Saving observation...",
  SUCCESSS_UPDATE: "Successfully Updated",
  // ---
  SHORTEN: "shorten",
  DEBOUNCE_TIME: 540,
  DAY_SELECTOR_STATE: "daySelectorState",
  // ---
  ERROR: "error",
  SUCCESS: "success",
  INFO: "info",
  WEB: "web",
  IOS: "ios",
  ANDROID: "android",
  INDEXED_INSPECTIONS: "indexedInspections",
  // ---
  ENUS: "en-US",
  // ---
  CODE: "code",
  STATE: "state",
  AUTH_CREDENTIALS: "authCredentials",
  OAUTH_TOKEN_URL: "/oauth2/token",
  OAUTH_MULTI_URL: "/oauth2/multi",
  INVALIDATE_TOKENS_URL: "/invalidateTokens",
  TIMELOG_URL: "/api/timelog",
  INSPECTIONS_URL: "/api/inspectionsms",
  TIMELOGMS: "timelog",
  INSPECTIONSMS: "inspectionsms",
  
};

export const SharedStyles = {
  mobileTableHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  } as any,
  tableHeader: {
    flexDirection: "row",
    backgroundColor: Colors.pdsRedLight,
  } as any,
  smallMobileTableHeader: {
    backgroundColor: Colors.pdsRedLight,
    paddingVertical: 0,
  } as any,
  tableHeaderCell: {
    flex: 1,
    padding: 10,
  } as any,
  smallMobileTableHeaderCell: {
    padding: 10,
    paddingVertical: 5,
  } as any,
  tableHeaderText: {
    marginVertical: 8,
    color: Colors.white,
    fontWeight: "bold",
  } as any,
  emptyTableRow: {
    overflow: "hidden",
    backgroundColor: Colors.pdsGrey,
    borderTopWidth: 1,
    borderColor: Colors.pdsGrey,
    padding: 20,
    textAlign: "center",
  } as any,
  lastTableItem: {
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
  } as any,
  buttonsContainer: {
    flexDirection: "row",
    width: "100%",
    gap: 15,
  },
};

export const InspectionDetailsStyles = {
  contentContainer: {
    flex: 1,
    backgroundColor: Colors.pdsBlack,
    padding: 20,
  }as any,
  text: {
    fontSize: 16,
    color: Colors.white,
  }as any,
  infoContainer: {
    backgroundColor: Colors.pdsGrey,
    marginTop: 5,
    paddingVertical: 15,
    paddingHorizontal: 15,
    borderRadius: 10,
    flexDirection: "row",
    flexWrap: "wrap",
  }as any,
  personTextDataContainer: {
    width: "50%",
    padding: 5,
  }as any,
  operatorsAndInspectorsContainer: {
    padding: 10,
    margin: 10,
    borderRadius: 12,
    backgroundColor: Colors.pdsGrey,
    flexWrap: "wrap",
    flexDirection: "column",
  }as any,
  buttonsContainer: {
    flexDirection: "column",
    justifyContent: "space-between",
    width: "100%",
    marginTop: 10,
    gap: 12,
  }as any,
  tabsContainer: {
    flexDirection: "row",
    marginVertical: 20,
    justifyContent: "space-between",
    paddingHorizontal: 3,
  }as any,
  textInfoContainer: {
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
    paddingRight: 2
  }as any,
  largeTextModalContent: {
    backgroundColor: Colors.pdsBlack,
    borderRadius: 10,
    padding: 20,
    paddingTop:15,
    width: "80%",
    maxHeight: "80%",
    borderWidth: 1,
    borderColor: Colors.pdsGrey2,
    gap: 6,
  }as any,
  largeTextModalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  }as any,
  autocomplete: {
    marginVertical:12,
    justifyContent: "space-between",
    alignItems: "center",
  }as any,
  autocompleteItem: {
    padding: 10,
    backgroundColor: Colors.pdsGrey2,
    width: "100%",
    borderTopWidth: 1,
    borderTopColor: Colors.statusGrey,
  }as any,
  autocompleteIcon: {
    position: "absolute",
    right: 10,
    top: 10,
  }as any,
  bottomButtonsContainer: {
    width: "100%", 
    marginVertical: 20, 
    flexDirection: "row", 
    justifyContent: "space-around"
  }as any,
  bottomSheetButtonsContainer: {
    padding: 10, 
    borderTopColor: Colors.pdsGrey2, 
    borderTopWidth: 1, 
    flexDirection: "row", 
    justifyContent: "space-around", 
    backgroundColor: Colors.sidebarBackgroundColor
  }as any,
  teamHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingTop: 6,
    marginBottom: 12,
  }as any
};